version: 0.2.0.{build}
os: Visual Studio 2017
install:
  - if not exist dotnet-dev-win-x64.latest.zip appveyor DownloadFile https://download.microsoft.com/download/0/6/5/0656B047-5F2F-4281-A851-F30776F8616D/dotnet-dev-win-x64.2.0.0-preview1-005977.zip -FileName "dotnet-dev-win-x64.2.0.0-preview1-005977.zip"  
  - cmd: 7z x dotnet-dev-win-x64.2.0.0-preview1-005977.zip -oc:\dotnet
  - docker version

before_build:
- cmd: git submodule update --init --recursive
- cmd: path c:\dotnet
- cmd: dotnet --info  

build_script:
- cmd: dotnet --info
- ps: $url1='https://img.shields.io/badge/version-v0.2.' + $env:APPVEYOR_BUILD_NUMBER  + '-blue.svg'
- ps: .\download.ps1 $url1 "latest-version-badge.svg"
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/zip/*.zip
- path: artifacts/nuget/*.nupkg
- path: latest-version-badge.svg

deploy:
- provider: Environment
  name: FastRing
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/e8ce2449e773a183903b
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
